package cookieprofiles

import (
	"bufio"
	"bytes"
	"errors"
	"fmt"
	"sort"
	"strconv"
	"strings"
	"unicode/utf8"
)

const maxCookieFileBytes = 5 * 1024 * 1024

type cloudCookie struct {
	Domain         string  `json:"domain"`
	HostOnly       bool    `json:"hostOnly"`
	HTTPOnly       bool    `json:"httpOnly"`
	Name           string  `json:"name"`
	Path           string  `json:"path"`
	Secure         bool    `json:"secure"`
	Session        bool    `json:"session"`
	Value          string  `json:"value"`
	ExpirationDate float64 `json:"expirationDate"`
}

type jarSummary struct {
	Content     []byte
	CookieCount int
	DomainCount int
}

func buildNetscapeJar(cookieData map[string][]cloudCookie) (jarSummary, error) {
	type line struct {
		domain string
		path   string
		name   string
		value  string
		text   string
	}
	lines := make([]line, 0)
	domains := map[string]struct{}{}

	for fallbackDomain, cookies := range cookieData {
		for _, cookie := range cookies {
			domain := strings.TrimSpace(cookie.Domain)
			if domain == "" {
				domain = strings.TrimSpace(fallbackDomain)
			}
			path := strings.TrimSpace(cookie.Path)
			if path == "" {
				path = "/"
			}
			if !safeCookieField(domain) || !safeCookieField(path) ||
				!safeCookieField(cookie.Name) || !safeCookieField(cookie.Value) ||
				cookie.Name == "" {
				continue
			}
			includeSubdomains := strings.HasPrefix(domain, ".") || !cookie.HostOnly
			expiry := int64(0)
			if !cookie.Session && cookie.ExpirationDate > 0 {
				expiry = int64(cookie.ExpirationDate)
			}
			outputDomain := domain
			if cookie.HTTPOnly {
				outputDomain = "#HttpOnly_" + outputDomain
			}
			text := strings.Join([]string{
				outputDomain,
				strconv.FormatBool(includeSubdomains),
				path,
				strconv.FormatBool(cookie.Secure),
				strconv.FormatInt(expiry, 10),
				cookie.Name,
				cookie.Value,
			}, "\t")
			text = strings.ReplaceAll(text, "true", "TRUE")
			text = strings.ReplaceAll(text, "false", "FALSE")
			lines = append(lines, line{
				domain: strings.TrimPrefix(strings.ToLower(domain), "."),
				path:   path,
				name:   cookie.Name,
				value:  cookie.Value,
				text:   text,
			})
			domains[strings.TrimPrefix(strings.ToLower(domain), ".")] = struct{}{}
		}
	}

	if len(lines) == 0 {
		return jarSummary{}, errors.New("CookieCloud 中没有可用于 yt-dlp 的 Cookie")
	}
	sort.Slice(lines, func(i, j int) bool {
		left := lines[i]
		right := lines[j]
		if left.domain != right.domain {
			return left.domain < right.domain
		}
		if left.path != right.path {
			return left.path < right.path
		}
		if left.name != right.name {
			return left.name < right.name
		}
		return left.value < right.value
	})

	var output strings.Builder
	output.WriteString("# Netscape HTTP Cookie File\n")
	output.WriteString("# Generated by Visoraft. Treat this file as a secret.\n\n")
	for _, item := range lines {
		output.WriteString(item.text)
		output.WriteByte('\n')
	}
	return jarSummary{
		Content:     []byte(output.String()),
		CookieCount: len(lines),
		DomainCount: len(domains),
	}, nil
}

func validateNetscapeJar(content []byte) (jarSummary, error) {
	if len(content) == 0 {
		return jarSummary{}, errors.New("Cookie 文件为空")
	}
	if len(content) > maxCookieFileBytes {
		return jarSummary{}, fmt.Errorf("Cookie 文件不能超过 %d MiB", maxCookieFileBytes/(1024*1024))
	}
	content = bytes.TrimPrefix(content, []byte{0xef, 0xbb, 0xbf})
	if !utf8.Valid(content) || bytes.IndexByte(content, 0) >= 0 {
		return jarSummary{}, errors.New("Cookie 文件必须是 UTF-8 文本")
	}
	content = bytes.ReplaceAll(content, []byte("\r\n"), []byte("\n"))
	content = bytes.ReplaceAll(content, []byte("\r"), []byte("\n"))

	scanner := bufio.NewScanner(bytes.NewReader(content))
	scanner.Buffer(make([]byte, 64*1024), maxCookieFileBytes)
	if !scanner.Scan() {
		return jarSummary{}, errors.New("Cookie 文件为空")
	}
	header := strings.TrimSpace(scanner.Text())
	if header != "# HTTP Cookie File" && header != "# Netscape HTTP Cookie File" {
		return jarSummary{}, errors.New(
			"Cookie 文件第一行必须是 # HTTP Cookie File 或 # Netscape HTTP Cookie File",
		)
	}

	lines := make([]string, 0)
	domains := map[string]struct{}{}
	lineNumber := 1
	for scanner.Scan() {
		lineNumber++
		line := strings.TrimSpace(scanner.Text())
		if line == "" || (strings.HasPrefix(line, "#") && !strings.HasPrefix(line, "#HttpOnly_")) {
			continue
		}
		fields := strings.Split(line, "\t")
		if len(fields) != 7 {
			return jarSummary{}, fmt.Errorf("Cookie 文件第 %d 行不是 7 列 Netscape 格式", lineNumber)
		}
		if fields[1] != "TRUE" && fields[1] != "FALSE" {
			return jarSummary{}, fmt.Errorf("Cookie 文件第 %d 行的子域标记无效", lineNumber)
		}
		if fields[3] != "TRUE" && fields[3] != "FALSE" {
			return jarSummary{}, fmt.Errorf("Cookie 文件第 %d 行的安全标记无效", lineNumber)
		}
		if _, err := strconv.ParseInt(fields[4], 10, 64); err != nil {
			return jarSummary{}, fmt.Errorf("Cookie 文件第 %d 行的有效期无效", lineNumber)
		}
		if fields[0] == "" || fields[2] == "" || fields[5] == "" {
			return jarSummary{}, fmt.Errorf("Cookie 文件第 %d 行缺少域名、路径或名称", lineNumber)
		}
		if !safeCookieField(fields[6]) {
			return jarSummary{}, fmt.Errorf("Cookie 文件第 %d 行包含非法换行或制表符", lineNumber)
		}
		lines = append(lines, strings.Join(fields, "\t"))
		domain := strings.TrimPrefix(fields[0], "#HttpOnly_")
		domains[strings.TrimPrefix(strings.ToLower(domain), ".")] = struct{}{}
	}
	if err := scanner.Err(); err != nil {
		return jarSummary{}, fmt.Errorf("读取 Cookie 文件失败：%w", err)
	}
	if len(lines) == 0 {
		return jarSummary{}, errors.New("Cookie 文件中没有有效 Cookie")
	}

	var output strings.Builder
	output.WriteString("# Netscape HTTP Cookie File\n")
	output.WriteString("# Stored by Visoraft. Treat this file as a secret.\n\n")
	for _, line := range lines {
		output.WriteString(line)
		output.WriteByte('\n')
	}
	return jarSummary{
		Content:     []byte(output.String()),
		CookieCount: len(lines),
		DomainCount: len(domains),
	}, nil
}

func safeCookieField(value string) bool {
	return !strings.ContainsAny(value, "\t\r\n\x00")
}
